### ISSUE TITLE
Opcnetdaaeserver displays an error when the client disconnects

### ISSUE THREAD

**Issue by kimdiego2098** [technosoftware-gmbh/opc-daae-server-solution#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I am developing a server

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

Opcnetdaaeserver displays an error when the client disconnects
![IZUUVS0SAL4EH1GW0O@`39](https://user-images.githubusercontent.com/82756760/168265218-218b4a38-32c9-4f4f-9a1b-5855c1d6360b.png)

# Failure Information (for bugs)
Opcnetdaaeserver displays an error when the client disconnects
{
abort0 has been called
}
## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

just regserver and connect,disconnect

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows10 
* SDK version: Last

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by technosoftware** [comment]
I have tried to reproduce it with Visual Studio 2019, .NET 4.8 and PlatformToolset v142 and it works fine.

Please debug on your side and provide more detailed information, e.g. where the exception happened.

**Comment by kimdiego2098** [comment]
VS2022, .net4.8  , PlatformToolset v142 and the examples version used by dasampleserver
Unfortunately, I can't debug C + +,but If I change the server to daonly, this error will not occur，This should be my problem, because net uses daserver instead of daaeserver

**Comment by technosoftware** [comment]
I used the same now but it works fine. So nothing I can do. Please debug the C++ code and check what is wrong.

**Comment by kimdiego2098** [comment]
Debug C + + code sees that the OnTerminateServer function is called twice ，Here are two screenshots of the last stack：
![20220515234938](https://user-images.githubusercontent.com/82756760/168481787-86b9e03f-e413-4314-bc97-528af0ab1539.png)

![20220515234941](https://user-images.githubusercontent.com/82756760/168481782-0e686374-fbe2-4031-9ff7-c282921c838f.png)

**Comment by kimdiego2098** [comment]
the ~CoreGenericMain is Last called

**Comment by kimdiego2098** [comment]
Debug error breakpoint location

![image](https://user-images.githubusercontent.com/82756760/168481942-8b0db81e-6119-4752-a278-0f497a53e240.png)

**Comment by technosoftware** [comment]
We removed DLL and .NET support

**Comment by kimdiego2098** [comment]
> 我们删除了 DLL 和 .NET 支持

emm,What is the reason

**Comment by technosoftware** [comment]
During updating to Visual Studio 2022 and trying to support newer .NET frameworks it seems that the support of (D)COM has heavily changed and the wrappers from OPC DA,AE and HDA to .NET doesn't work any longer as expected. 

For the client part we found an issue in the OPC Core Components from the OPC Foundation which made clients no longer be able to connect to servers. Happens with .NET 5.0, .NET 6.0 and .NET 7.0. See also [here](https://github.com/technosoftware-gmbh/opcdaaehda-solution-net/issues/58). That issue is even not possible to fix on our side.

Because of this we decided to removed .NET support from the server part. A fully C++ server is still working fine.

**Comment by kimdiego2098** [comment]
Ok, is still support net48? If so, I don't think it should be deleted

**Comment by technosoftware** [comment]
Version 2 is still available in branch [release/2.0](https://github.com/technosoftware-gmbh/opc-daae-server-solution/tree/release/2.0).

But with Visual Studio 2022 and version 3 we will not do any effort to try to get that running, also not for .NET frameworks 4.6.2, 4.7.2 or 4.8.

**Comment by kimdiego2098** [comment]
i see，and a Copyright problem: I have an open source project that wants to integrate this opc da server project. Is there a copyright problem? In addition, can I modify the copyright logo in the source code

**Comment by technosoftware** [comment]
Regarding examples in the examples directory that is no problem. The rest should stay, specially in the src directory.
